/**
 * Bundled math fallback font: STIX Two Math (SIL OFL 1.1).
 *
 * v1 ships the full STIX Two Math TTF (~1.5 MB) rather than a subset.
 * This bloats the bundle but guarantees coverage of every Unicode math
 * codepoint — every big-op, fence, alphanumeric variant, and operator
 * the layout engine might ask for. Subsetting to the v1 codepoint
 * ranges (~80–120 KB target) is a follow-up — see spec §7.1.
 *
 * Generated by `scripts/build-math-fallback-font.mjs` from
 * `assets/fonts/stix-two-math.ttf`. License: examples/OFL_STIXTwoMath.txt.
 */
import {mathStixFallbackBytes} from '../../fonts/fallback/math';

/** Alias used to register the bundled math font in the SlugFonts registry. */
export const MATH_FALLBACK_ALIAS = '__slug_math_fallback__' as const;

/** Bytes used as the default math font. */
export const mathFallbackBytes: Uint8Array = mathStixFallbackBytes;
