import './slug/fonts/ticker';
export {SlugFont} from '../shared/slug/font';
export {SlugFonts} from '../shared/slug/fonts';
export {SlugText} from './slug/text';
export {slugShader} from './slug/shader';
export {slugFontGpuV6} from './slug/font/gpu';
export type {SlugFontGpuV6} from './slug/font/gpu';
export {slugFontsAttachTickerV6} from './slug/fonts/ticker';
export {slugFontsFetchV6} from './slug/fonts/loader';
export {SlugApplicationPluginV6} from './slug/plugin';
