import './slug/fonts/ticker';
export {SlugFont} from '../shared/slug/font';
export {SlugFonts} from '../shared/slug/fonts';
export {SlugText} from './slug/text';
export {slugShader} from './slug/shader';
export {slugFontGpuV6} from './slug/font/gpu';
export type {SlugFontGpuV6} from './slug/font/gpu';
export {slugFontsAttachTickerV6} from './slug/fonts/ticker';
export {slugFontsFetchV6} from './slug/fonts/loader';
export {SlugApplicationPluginV6} from './slug/plugin';
export {slugFontErrorRaise} from '../shared/slug/font/error/raise';
export type {SlugFontErrorPolicy} from '../shared/slug/font/error/policy';
export type {SlugFontErrorCase} from '../shared/slug/font/error/case';
export type {SlugFontErrorMode} from '../shared/slug/font/error/mode';
export type {Rgba, RgbaReadonly} from '../rgba';
export type {SlugFontsRemoveResult} from '../shared/slug/fonts/remove';
